SELECT * FROM customer_relation_management_db.`wa_fn-usec_-customer_relationship`;
-- dataset: https://www.kaggle.com/datasets/pankajjsh06/ibm-watson-marketing-customer-value-data

RENAME TABLE `IBM_Customer_Relationship_Management` TO IBM_Customer_Relationship_Management;


select * from IBM_Customer_Relationship_Management;

alter table IBM_Customer_Relationship_Management
change column `Effective To Date`  effective_to_date text;

alter table IBM_Customer_Relationship_Management
change column `Customer Lifetime Value`  Customer_Lifetime_Value text;

describe IBM_Customer_Relationship_Management;

SELECT STR_TO_DATE('2/24/11', '%m/%d/%y');


update IBM_Customer_Relationship_Management
SET effective_to_date = STR_TO_DATE( '%m/%d/%y'); -- wrong method

ALTER TABLE IBM_Customer_Relationship_Management
MODIFY COLUMN effective_to_date DATE;

select count(Customer) from IBM_Customer_Relationship_Management;

-- 1. Find Customers with Most Recent Interactions
-- This query retrieves customers who have interacted most recently with your business.


select Customer, month(effective_to_date) as Most_recent_relation from IBM_Customer_Relationship_Management
where month(effective_to_date)= 2;


-- 2. Find the Total Revenue Generated by Customers in a Specific Time Period

select sum(income) as Reveune from IBM_Customer_Relationship_Management;


select Months_Since_Last_Claim, sum(Income) as Total_income from IBM_Customer_Relationship_Management
where Months_Since_Last_Claim > 12
group by Months_Since_Last_Claim
order by Months_Since_Last_Claim desc limit 10;



-- 3. List of Active Customers (Based on claims made)

select * from IBM_Customer_Relationship_Management;

select Customer, Total_Claim_Amount,Months_Since_Last_Claim,Monthly_Premium_Auto  
from IBM_Customer_Relationship_Management order by Total_Claim_Amount desc limit 5;




-- 3. Customer Lifetime Value by Coverage Type

select Coverage, sum(Customer_Lifetime_Value) as Total_CLV from IBM_Customer_Relationship_Management
group by Coverage;



-- 4. Count of Customers in Each Coverage Category:

select Coverage,count(Customer)as Total_customer from IBM_Customer_Relationship_Management
group by Coverage;



/* 5. Customer Segmentation: Number of Policies vs. Customer Lifetime Value
Query: Group customers by EmploymentStatus and calculate total policies and average lifetime value.  */

select EmploymentStatus, sum(Number_of_Policies) as Total_No_policies, Avg(Customer_Lifetime_Value) as Average_CLV
 from IBM_Customer_Relationship_Management
 group by EmploymentStatus;
 
 
 
 /*  6. Find Customers with High Lifetime Value
Query: Get customers with a Customer_Lifetime_Value greater than a specific threshold (e.g., 1000).  */

select customer, Customer_Lifetime_Value from IBM_Customer_Relationship_Management
where Customer_Lifetime_Value > 2000;



-- 7. Average Premium by Employment Status
select EmploymentStatus, round(avg(Monthly_Premium_Auto),2) as Average_premium_employeed_status
from IBM_Customer_Relationship_Management
group by EmploymentStatus;



-- 9. Top 5 Customers by Lifetime Value

select customer, Customer_Lifetime_Value as CLV_Highest from IBM_Customer_Relationship_Management
order by CLV_Highest desc limit 5;



-- 10. Customer Count by Region (if applicable)

select state, count(Customer) as Total_cus_by_state
from IBM_Customer_Relationship_Management
group by state;



-- 11. Find Coverage Types with More Policies

select Coverage, sum(Number_of_Policies) as Total_number_of_policies
from IBM_Customer_Relationship_Management
group by Coverage
having sum(Number_of_Policies)> 34;



-- 12. Customers with Missing Data for Specific Columns
-- Query: Get a list of customers who have missing values for Customer_Lifetime_Value.

select customer, Customer_Lifetime_Value from IBM_Customer_Relationship_Management
where Customer_Lifetime_Value is null;



-- 13. Distribution of Customers by Income (Assuming there's an Income Column)

select * from IBM_Customer_Relationship_Management;

select 
 case 	
		when Income< 20000 then 'Low Income'
        when Income between 20000 and 50000 then 'Medium Income'
        else 'Higher Income'
        end as Income_group, count(Customer)
        from IBM_Customer_Relationship_Management
        group by Income_group
        order by Income_group;
        
        
        
-- 14. Average Policies per Customer by Coverage Type (Joins)
-- Query: Calculate the average number of policies per customer for each Coverage type.

SELECT Coverage, 
       AVG(Number_of_Policies) AS Avg_Policies_Per_Customer
FROM IBM_Customer_Relationship_Management
GROUP BY Coverage;




-- 15.Top 3 Coverage Types with Highest Total Policies (Subquery)

SELECT Coverage, 
       SUM(Number_of_Policies) AS Total_Policies
FROM IBM_Customer_Relationship_Management
GROUP BY Coverage
ORDER BY Total_Policies DESC
LIMIT 3;



-- 16 Find the Average Number of Policies for Each Employment Status with a Subquery:
SELECT EmploymentStatus, 
       AVG(Number_of_Policies) AS Avg_Policies
FROM IBM_Customer_Relationship_Management
group by EmploymentStatus;



-- 17. 4. Customers with the Highest and Lowest Premiums by Employment Status (Subquery)
-- Query: Find the customer with the highest and lowest Monthly_Premium_Auto for each EmploymentStatus.



SELECT EmploymentStatus, -- unable to run
       Customer, 
       Monthly_Premium_Auto
FROM IBM_Customer_Relationship_Management
WHERE (EmploymentStatus, Monthly_Premium_Auto) IN (
    SELECT EmploymentStatus, MAX(Monthly_Premium_Auto)
    FROM IBM_Customer_Relationship_Management
    GROUP BY EmploymentStatus
)
OR (EmploymentStatus, Monthly_Premium_Auto) IN (
    SELECT EmploymentStatus, MIN(Monthly_Premium_Auto)
    FROM IBM_Customer_Relationship_Management
    GROUP BY EmploymentStatus
);







-- ********************************************************************************************************************************************* --
--  Find Top 5 Customers by Total Spent

select customer, policy, Total_Claim_Amount, Vehicle_Class,Vehicle_Size 
from IBM_Customer_Relationship_Management
order by Total_Claim_Amount limit 5;


-- find the Total premium alter by M and F and 


select gender, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from IBM_Customer_Relationship_Management
group by gender;

select Education, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from IBM_Customer_Relationship_Management
group by Education;

select state, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from IBM_Customer_Relationship_Management
group by state;

select Coverage, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from IBM_Customer_Relationship_Management
group by Coverage;


select * from IBM_Customer_Relationship_Management;


-- Total customer Vs state wise
select state, sum(Customer_Lifetime_Value) as Total_cus_vale from IBM_Customer_Relationship_Management
group by state;




-- total customer vale and preimum state wise and policy coverage wise
select state, sum(Income),Coverage,sum(Customer_Lifetime_Value) as Total_customer_value_state,sum(Monthly_Premium_Auto)  as Total_premium_state
from IBM_Customer_Relationship_Management
group by state, Total_customer_value_state;

select * from IBM_Customer_Relationship_Management;

-- find the number of ploicies take by employee and unemployeed

select * from IBM_Customer_Relationship_Management;

select EmploymentStatus, sum(Number_of_Policies) as Total_plocies_taken
 from IBM_Customer_Relationship_Management
group by EmploymentStatus;

select * from IBM_Customer_Relationship_Management;


-- Total no of plocies under each coverage
select Coverage , sum(Number_of_Policies) as Total_Policies_Takes from IBM_Customer_Relationship_Management
group  by Coverage;

