SELECT * FROM customer_relation_management_db.`wa_fn-usec_-customer_relationship`;
-- dataset: https://www.kaggle.com/datasets/pankajjsh06/ibm-watson-marketing-customer-value-data

RENAME TABLE `wa_fn-usec_-customer_relationship` TO customer_relationship_Mng;


select * from customer_relationship_mng;

alter table customer_relationship_mng
change column `Effective To Date`  effective_to_date text;

alter table customer_relationship_mng
change column `Customer Lifetime Value`  Customer_Lifetime_Value text;

describe customer_relationship_mng;

SELECT STR_TO_DATE('2/24/11', '%m/%d/%y');


update customer_relationship_mng
SET effective_to_date = STR_TO_DATE( '%m/%d/%y');

ALTER TABLE customer_relationship_mng
MODIFY COLUMN effective_to_date DATE;

-- 1. Find Customers with Most Recent Interactions
-- This query retrieves customers who have interacted most recently with your business.

select * from customer_relationship_mng;

select Customer, month(effective_to_date) as Most_recent_relation from customer_relationship_mng
where month(effective_to_date)= 2;

-- 2. Find the Total Revenue Generated by Customers in a Specific Time Period
select * from customer_relationship_mng;

select Months_Since_Last_Claim, sum(Income) as Total_income from customer_relationship_mng
where Months_Since_Last_Claim > 12
group by 1
order by 1 desc limit 10;

-- 3. List of Active Customers (Based on claims made)

select * from customer_relationship_mng;

select Customer, Total_Claim_Amount,Months_Since_Last_Claim,Monthly_Premium_Auto  
from customer_relationship_mng order by 2 desc limit 5;



-- 3. Customer Lifetime Value by Coverage Type


select * from customer_relationship_mng;

select Coverage, sum(Customer_Lifetime_Value) as Total_CLV from customer_relationship_mng
group by 1;

-- 4. Count of Customers in Each Coverage Category:

select Coverage,count(Customer)as Total_customer from customer_relationship_mng
group by 1;

/* 5. Customer Segmentation: Number of Policies vs. Customer Lifetime Value
Query: Group customers by EmploymentStatus and calculate total policies and average lifetime value.  */

select EmploymentStatus, sum(Number_of_Policies) as Total_No_policies, Avg(Customer_Lifetime_Value) as Average_CLV
 from customer_relationship_mng
 group by EmploymentStatus;
 
 /*  6. Find Customers with High Lifetime Value
Query: Get customers with a Customer_Lifetime_Value greater than a specific threshold (e.g., 1000).  */

select customer, Customer_Lifetime_Value from customer_relationship_mng
where Customer_Lifetime_Value > 2000;

-- 7. Average Premium by Employment Status
select EmploymentStatus, round(avg(Monthly_Premium_Auto),2) as Average_premium_employeed_status
from customer_relationship_mng
group by 1;

-- 9. Top 5 Customers by Lifetime Value

select customer, Customer_Lifetime_Value as CLV_Highest from customer_relationship_mng
order by 2 desc limit 5;

-- 10. Customer Count by Region (if applicable)

select state, count(Customer) as Total_cus_by_state
from customer_relationship_mng
group by 1;

-- 11. Find Coverage Types with More Policies

select Coverage, sum(Number_of_Policies) as Total_number_of_policies
from customer_relationship_mng
group by 1
having sum(Number_of_Policies)> 34;

-- 12. Customers with Missing Data for Specific Columns
-- Query: Get a list of customers who have missing values for Customer_Lifetime_Value.

select customer, Customer_Lifetime_Value from customer_relationship_mng
where Customer_Lifetime_Value is null;

-- 13. Distribution of Customers by Income (Assuming there's an Income Column)

select * from customer_relationship_mng;

select 
 case 	
		when Income< 20000 then 'Low Income'
        when Income between 20000 and 50000 then 'Medium Income'
        else 'Higher Income'
        end as Income_group, count(Customer)
        from customer_relationship_mng
        group by 1;
        
        
-- 14. Average Policies per Customer by Coverage Type (Joins)
-- Query: Calculate the average number of policies per customer for each Coverage type.

SELECT Coverage, 
       AVG(Number_of_Policies) AS Avg_Policies_Per_Customer
FROM customer_relationship_mng
GROUP BY Coverage;


select count(distinct customer) from customer_relationship_mng;

select count(customer) from customer_relationship_mng;

-- 15.Top 3 Coverage Types with Highest Total Policies (Subquery)

SELECT Coverage, 
       SUM(Number_of_Policies) AS Total_Policies
FROM customer_relationship_mng
GROUP BY Coverage
ORDER BY Total_Policies DESC
LIMIT 3;



-- 16 Find the Average Number of Policies for Each Employment Status with a Subquery:
SELECT EmploymentStatus, 
       AVG(Number_of_Policies) AS Avg_Policies
FROM customer_relationship_mng
group by 1;



-- 17. 4. Customers with the Highest and Lowest Premiums by Employment Status (Subquery)
-- Query: Find the customer with the highest and lowest Monthly_Premium_Auto for each EmploymentStatus.



SELECT EmploymentStatus, -- unable to run
       Customer, 
       Monthly_Premium_Auto
FROM customer_relationship_mng
WHERE (EmploymentStatus, Monthly_Premium_Auto) IN (
    SELECT EmploymentStatus, MAX(Monthly_Premium_Auto)
    FROM customer_relationship_mng
    GROUP BY EmploymentStatus
)
OR (EmploymentStatus, Monthly_Premium_Auto) IN (
    SELECT EmploymentStatus, MIN(Monthly_Premium_Auto)
    FROM customer_relationship_mng
    GROUP BY EmploymentStatus
);



















-- ********************************************************************************************************************************************* --
--  Find Top 5 Customers by Total Spent

select customer, policy, Total_Claim_Amount, Vehicle_Class,Vehicle_Size 
from customer_relationship_mng
order by 3 limit 5;

-- find the Total premium alter by emloyed and un employed
select EmploymentStatus, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from customer_relationship_mng
group by 1;

select * from customer_relationship_mng;

-- find the Total premium alter by M and F and 
select gender, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from customer_relationship_mng
group by 1;

select Education, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from customer_relationship_mng
group by 1;

select state, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from customer_relationship_mng
group by 1;

select Coverage, sum(Monthly_Premium_Auto) as Total_monthly_premium  
from customer_relationship_mng
group by 1;


select * from customer_relationship_mng;

-- Total customer vale state wise
select state, sum(Customer_Lifetime_Value) as Total_cus_vale from customer_relationship_mng
group by 1;


-- total customer vale and preimum state wise and policy coverage wise
select state, sum(Income),Coverage,sum(Customer_Lifetime_Value) as Total_customer_value_state,sum(Monthly_Premium_Auto)  as Total_premium_state
from customer_relationship_mng
group by 1,3;

select * from customer_relationship_mng;

-- find the number of ploicies take by employee and unemployeed

select * from customer_relationship_mng;

select EmploymentStatus, sum(Number_of_Policies) as Total_plocies_taken
 from customer_relationship_mng
group by 1;

select * from customer_relationship_mng;

-- Total no of plocies under each coverage
select Coverage , sum(Number_of_Policies) as Total_Policies_Takes from customer_relationship_mng
group  by 1;


